### ISSUE TITLE
Parameter Diagnostics

### ISSUE THREAD

**Issue by stofe95** [crtwomey/paws#1]
I've been trying to use PAWS on my data to track withdrawals and it works quite well, but I feel like it could benefit from an added feature. Setting the parameters for the filters seems like a bit of a shot in the dark right now. All you can seem to do is look at the output features and try to see if it matches your data well, but this doesn't fill me with a lot of confidence. Maybe some features for plotting the detected shakes and peaks on the xy trajectories would make it easier for the user to determine whether the filter sizes they are using are appropriate. It seems from your publication that you have already done this, so maybe adding this plotting would make it easier to use and be confident that the output features are accurate.

**Comment by crtwomey** [comment]
Thanks for this suggestion! I've finally added better diagnostic plots (in particular for shaking and guarding; added in commit d6feb02594597b9c724db068660afbef599e5544), and better documentation in the project readme (README.md) about diagnostics and parameter tuning (added in commit 2d99e4c6e90d8ca61fba60a5cf75329ff39502a3). There are further improvements I'd like to make to this process but they'll have to wait until I have time again to work on this. I hope these changes help for now.
